apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  labels:
    app.kubernetes.io/name: loadtest
    app.kubernetes.io/managed-by: github-actions
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
