---
aws_region: us-east-1
project_name: githubActions-EKS

# VPC
vpc_cidr: "10.0.0.0/20"
vpc_name: "githubActions-EKS"

# Subnets públicas (6 subnets en 3 AZs, 2 por AZ)
subnets:
  - cidr: "10.0.0.0/23"
    az: "{{ aws_region }}a"
    name: "githubActions-EKS-public-1a"
  - cidr: "10.0.2.0/23"
    az: "{{ aws_region }}b"
    name: "githubActions-EKS-public-1b"
  - cidr: "10.0.4.0/23"
    az: "{{ aws_region }}c"
    name: "githubActions-EKS-public-1c"
  - cidr: "10.0.6.0/23"
    az: "{{ aws_region }}a"
    name: "githubActions-EKS-public-2a"
  - cidr: "10.0.8.0/23"
    az: "{{ aws_region }}b"
    name: "githubActions-EKS-public-2b"
  - cidr: "10.0.10.0/23"
    az: "{{ aws_region }}c"
    name: "githubActions-EKS-public-2c"

# EKS
eks_cluster_name: "githubActions-EKS"
eks_version: "1.29"

# Fargate
fargate_profile_name: "githubActions-EKS-fargate"
fargate_namespace: "default"
